(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slug(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function render(){
 const c=window.COUNTRY_CONTENT,root=document.getElementById('country-content');if(!c||!root)return;
 document.title=`${c.name} | Guías, itinerarios y planifica tu viaje | Viajando con Cabeza`;
 const facts=(c.facts||[]).map(x=>`<div class="country-fact"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join('');
 const guides=(c.guides||[]).map((g,i)=>`<article class="country-guide-card ${i===0?'featured':''}" data-guide="${esc(slug(g.title))}"><img src="${esc(g.image)}" alt="${esc(g.title)}"><div class="country-guide-copy"><span class="tag">${esc(g.tag)}</span><h3>${esc(g.title).toUpperCase()}</h3><p>${esc(g.text)}</p><div class="country-meta"><span>◷ ${esc(g.days)}</span><span>€ ${esc(g.budget)}</span></div>${g.available?`<a class="country-btn" href="${esc(g.href)}">VER GUÍA →</a>`:'<span class="country-soon">PRÓXIMAMENTE</span>'}</div></article>`).join('');
 const its=(c.itineraries||[]).map(i=>i.href?`<article class="country-itinerary"><img src="${esc(i.image)}" alt="${esc(i.title)}"><div class="country-itinerary-copy"><span class="tag">${esc(i.tag)}</span><h3>${esc(i.title).toUpperCase()}</h3><p>${esc(i.text)}</p><a href="${esc(i.href)}">VER ITINERARIO →</a></div></article>`:`<div class="country-coming"><div><strong>${esc(i.title).toUpperCase()}</strong><span>${esc(i.text)}</span></div></div>`).join('');
 const planning=(c.planning||[]).map(p=>`<div class="country-plan-card"><b>${esc(p[0])}</b><span>${esc(p[1])}</span></div>`).join('');
 const tips=(c.savingTips||[]).map(t=>`<article class="saving-card"><span>${t[0]}</span><h3>${esc(t[1])}</h3><p>${esc(t[2])}</p><b>${esc(t[3])}</b></article>`).join('');
 let budget='';if(c.budgetExample){const b=c.budgetExample,rows=(b.items||[]).map(x=>`<div><b>${esc(x[0])}</b><strong>${esc(x[1])}</strong></div>`).join('');budget=`<div class="budget-example"><span>${esc(b.label)}</span>${rows}<div class="budget-total"><b>TOTAL REAL</b><strong>${esc(b.total)}</strong></div>${b.href&&b.href!=='#'?`<a href="${esc(b.href)}">VER PRESUPUESTO →</a>`:''}</div>`}
 let planner='';
 if(c.planner){const p=c.planner;planner=`<div class="trip-planner" data-trip-planner><div class="planner-intro"><span class="planner-kicker">PLANIFICADOR</span><h3>¿CÓMO QUIERES QUE SEA TU VIAJE A ${esc(c.name).toUpperCase()}?</h3><p>Elige tus preferencias y te recomendaremos las guías e itinerarios de nuestra web que mejor encajan contigo.</p></div><form class="planner-form"><label>¿Cuándo viajas?<select name="month"><option value="">Me da igual</option>${(p.months||[]).map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}</select></label><label>¿Cuántos días tienes?<select name="days">${(p.days||[]).map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}</select></label><label>¿Qué presupuesto tienes?<select name="budget"><option value="">Me da igual</option>${(p.budgets||[]).map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}</select></label><fieldset><legend>¿Qué te apetece?</legend><div class="planner-checks">${(p.interests||[]).map(x=>`<label><input type="checkbox" name="interest" value="${esc(x.value)}"><span>${esc(x.label)}</span></label>`).join('')}</div></fieldset><label>¿Cómo quieres moverte?<select name="transport"><option value="">Me da igual</option>${(p.transports||[]).map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}</select></label><button type="submit">ENCONTRAR MI VIAJE →</button></form><div class="planner-result" hidden aria-live="polite"></div></div>`}
 root.innerHTML=`<section class="country-hero" style="background-image:url('${esc(c.heroImage)}')"><div class="country-hero-inner"><div class="country-breadcrumb"><a href="../../index.html">Inicio</a><span>›</span><a href="../index.html">Destinos</a><span>›</span><strong>${esc(c.name)}</strong></div><div class="country-hero-card"><div class="country-eyebrow">📍 ${esc(c.continent).toUpperCase()}</div><h1>${esc(c.name).toUpperCase()}</h1><p class="country-script">${esc(c.tagline)}</p><p class="country-desc">${esc(c.description)}</p><div class="country-facts">${facts}</div></div></div></section><nav class="country-nav"><div class="country-nav-inner"><a href="#guias">GUÍAS</a><a href="#itinerarios">ITINERARIOS</a><a href="#planifica">PLANIFICA TU VIAJE</a></div></nav><main class="country-main"><section id="guias"><div class="country-heading"><div><p>Descubre ${esc(c.name)}</p><h2>GUÍAS DE ${esc(c.name).toUpperCase()}</h2></div><span>Guías por ciudades, regiones y zonas para preparar cada parte del viaje con detalle.</span></div><div class="country-guide-grid">${guides}</div></section><section id="itinerarios"><div class="country-heading"><div><p>Rutas listas para usar</p><h2>ITINERARIOS EN ${esc(c.name).toUpperCase()}</h2></div><span>Rutas de una sola zona o combinaciones de varias guías. Puedes seguirlas tal cual o usarlas para construir tu propio viaje.</span></div><div class="country-itineraries">${its}</div></section><section id="planifica"><div class="country-heading"><div><p>Tu viaje, a tu manera</p><h2>PLANIFICA ${esc(c.name).toUpperCase()}</h2></div><span>Mes, días, presupuesto y tipo de viaje: utiliza nuestras guías e itinerarios como piezas para encontrar la combinación que mejor encaja contigo.</span></div>${planner}<div class="country-planning">${planning}</div>${tips?`<div class="planifica-saving"><div class="country-heading compact"><div><p>Gasta con cabeza</p><h2>AHORRA SIN RENUNCIAR AL VIAJE</h2></div><span>Consejos prácticos de presupuesto integrados dentro de la planificación.</span></div><div class="saving-grid">${tips}</div>${budget}</div>`:''}</section><div class="country-footer-space"></div></main>`;
 if(c.planner)setupPlanner(c);
}
function setupPlanner(c){const box=document.querySelector('[data-trip-planner]');if(!box)return;const form=box.querySelector('form'),out=box.querySelector('.planner-result'),items=[...(c.planner.items||[])];form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),month=fd.get('month')||'',days=parseInt(fd.get('days')||'0',10),budget=fd.get('budget')||'',transport=fd.get('transport')||'',interests=fd.getAll('interest');const ranked=items.map(item=>{let score=0;if(month&&(!item.months||item.months.includes(month)))score+=3;if(budget&&(!item.budgets||item.budgets.includes(budget)))score+=2;if(transport&&(!item.transports||item.transports.includes(transport)))score+=2;if(days&&item.minDays!=null&&item.maxDays!=null){if(days>=item.minDays&&days<=item.maxDays)score+=5;else score+=Math.max(0,3-Math.abs(days-((item.minDays+item.maxDays)/2)))}score+=interests.filter(x=>(item.interests||[]).includes(x)).length*3;return {...item,score}}).sort((a,b)=>b.score-a.score).slice(0,3);const chosen=[];let remaining=days;for(const r of ranked){if(!days||chosen.length===0||remaining>0){chosen.push(r);remaining-=Math.min(Math.max(r.minDays||1,1),Math.max(remaining,0))}if(chosen.length>=3)break}const cards=chosen.map((r,i)=>`<article class="planner-result-card"><span>${i===0?'MEJOR ENCAJE':'TAMBIÉN ENCAJA'}</span><h4>${esc(r.title)}</h4><p>${esc(r.text||'')}</p><small>${r.minDays&&r.maxDays?`${r.minDays===r.maxDays?r.minDays:`${r.minDays}–${r.maxDays}`} días recomendados`:''}</small>${r.href?`<a href="${esc(r.href)}">VER ${r.type==='guide'?'GUÍA':'ITINERARIO'} →</a>`:''}</article>`).join('');out.innerHTML=`<div class="planner-result-head"><p class="country-script">Nuestra recomendación ♡</p><h3>${days?`${days} DÍAS EN ${esc(c.name).toUpperCase()}`:`IDEAS PARA TU VIAJE A ${esc(c.name).toUpperCase()}`}</h3><p>No hace falta que exista un único itinerario exacto: puedes combinar estas piezas según el tiempo que tengas.</p></div><div class="planner-results-grid">${cards}</div>`;out.hidden=false;out.scrollIntoView({behavior:'smooth',block:'nearest'})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();