(function(){
  const c=window.ROUTE_DAY_CONFIG;if(!c)return;
  const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const days=[['dia-1-salzburg/','DÍA 1 · SALZBURG'],['dia-2-st-wolfgang-hallstatt/','DÍA 2 · LAGOS'],['dia-3-berchtesgaden-innsbruck/','DÍA 3 · ALEMANIA'],['dia-4-innsbruck-zurich/','DÍA 4 · INNSBRUCK'],['dia-5-zurich/','DÍA 5 · ZÚRICH']];
  const root='../';
  const tabs=days.map((d,i)=>`<a href="${root+d[0]}"${i+1===c.day?' class="active" aria-current="page"':''}>${d[1]}</a>`).join('');
  const schedule=c.schedule.map(s=>`<div class="sched-item"><div class="sched-time">${esc(s[0])}</div><div class="sched-copy"><h4>${esc(s[1])}</h4><p>${esc(s[2])}</p></div></div>`).join('');
  const cards=c.cards.map(card=>`<section class="info-card"><small>${esc(card.label)}</small><h3>${esc(card.title)}</h3>${card.lines.map(line=>`<p>${line}</p>`).join('')}</section>`).join('');
  const prev=c.day>1?`<a href="${root+days[c.day-2][0]}">← DÍA ${c.day-1}</a>`:'<span></span>';
  const next=c.day<5?`<a href="${root+days[c.day][0]}">DÍA ${c.day+1} →</a>`:'<span></span>';
  document.body.innerHTML=`<header class="page-header"></header><section class="route-hero" style="background-image:url('${c.hero}')"><div class="route-hero-inner"><div class="route-crumb"><a href="../">RUTA DE NAVIDAD EN 5 DÍAS</a> &nbsp;›&nbsp; DÍA ${c.day}</div><div class="route-kicker">Nuestra ruta real</div><h1>${esc(c.place)}</h1><p>${esc(c.meta)}</p><div class="route-facts"><span>▣ DÍA ${c.day} DE 5</span>${c.facts.map(x=>`<span>${esc(x)}</span>`).join('')}<span>♡ RUTA VCC</span></div></div></section><nav class="route-day-tabs" aria-label="Días del itinerario">${tabs}</nav><main class="route-shell"><div class="route-intro"><div><small>Paso a paso</small><h2>${esc(c.heading)}</h2></div><p>${esc(c.summary)}</p></div><div class="route-layout"><article class="day-card"><header class="day-card-header"><div class="day-number">DÍA <b>${c.day}</b></div><div class="day-title"><h3>${esc(c.cardTitle)}</h3><p>${esc(c.meta)}</p></div><div class="day-badge">RUTA VCC</div></header><div class="day-body"><p class="day-desc">${esc(c.description)}</p><h3 class="schedule-heading">Programa hora a hora</h3><p class="schedule-sub">El orden que seguimos durante esta jornada.</p><div class="schedule">${schedule}</div><nav class="day-bottom-nav">${prev}<a class="all-days" href="../">VER RUTA COMPLETA</a>${next}</nav></div></article><aside class="route-aside">${cards}<section class="info-card route-note"><small>NUESTRO PLANNING</small><h3>A tener en cuenta</h3><p>${esc(c.note)}</p></section></aside></div></main><footer class="route-footer"><div class="route-footer-inner"><div><small>¿Seguimos viajando?</small><h2>DESCUBRE LA RUTA COMPLETA</h2></div><a href="../">VOLVER AL ITINERARIO →</a></div></footer>`;
  const script=document.createElement('script');script.src='../../../js/site-header.js';document.body.appendChild(script);
})();
