window.COUNTRY_CONFIG={
 slug:'austria',name:'Austria',continent:'Europa',tagline:'Mercados de Navidad, Alpes y pueblos de postal',description:'Nuestra ruta por Austria con guías de Salzburg, St. Wolfgang, Hallstatt e Innsbruck.',heroImage:'https://images.unsplash.com/photo-1504218727796-db522606b16f?auto=format&fit=crop&w=1800&q=88',inspirationImage:'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=1800&q=86',paths:{home:'../../index.html',destinations:'../index.html'},
 sections:{guides:{kicker:'Descubre Austria',title:'GUÍAS DE VIAJE',description:'Las ciudades y lugares que formaron parte de nuestra ruta de Navidad.'},itineraries:{kicker:'Nuestra ruta',title:'ITINERARIOS EN AUSTRIA',description:'El recorrido completo, conectado día a día con Alemania y Suiza.',minimumCards:4},preparation:{kicker:'Antes de viajar a Austria',title:'PLANIFICA TU VIAJE',description:'Lo que utilizamos para organizar transportes, alojamiento y días de invierno.'},inspiration:{line1:'Viaja mejor,',line2:'viaja con cabeza'},faq:{kicker:'Antes de viajar',title:'PREGUNTAS FRECUENTES',description:'Notas prácticas de nuestra ruta por Austria.',sideLine1:'Viajar mejor',sideLine2:'empieza con',sideLine3:'buenas preguntas'}},
 facts:[['CAPITAL','Viena'],['IDIOMA','Alemán'],['MONEDA','Euro · EUR'],['NUESTRA RUTA','4 días']],
 guides:[
 {title:'Salzburg',tag:'CIUDAD',image:'https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=1000&q=88',text:'Centro histórico, miradores, fortaleza y mercados de Navidad.',days:'2 noches',scores:{experience:9,photogenic:9,things:9,food:8,transport:9,safety:9,value:8},available:true,href:'salzburg/'},
 {title:'St. Wolfgang',tag:'EXCURSIÓN',image:'https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=1000&q=88',text:'Wolfgangsee y una parada alpina antes de continuar hacia Hallstatt.',days:'1 mañana',scores:{experience:9,photogenic:9.5,things:8,food:8,transport:8,safety:9,value:8},available:true,href:'st-wolfgang/'},
 {title:'Hallstatt',tag:'EXCURSIÓN',image:'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=1000&q=88',text:'Lago, miradores y una tarde dentro de nuestra excursión desde Salzburg.',days:'1 tarde',scores:{experience:9,photogenic:10,things:8.5,food:8,transport:8,safety:9,value:8},available:true,href:'hallstatt/'},
 {title:'Innsbruck',tag:'CIUDAD',image:'https://images.unsplash.com/photo-1596394723269-b2cbca4e6313?auto=format&fit=crop&w=1000&q=88',text:'Centro histórico, Bergisel, Ambras y Hungerburg antes de seguir hacia Zúrich.',days:'1 noche + 1 día',scores:{experience:9,photogenic:9.5,things:9,food:8,transport:9,safety:9,value:8},available:true,href:'innsbruck/'}],
 itineraries:[{title:'Austria, Alemania y Suiza en 5 días',tag:'5 DÍAS · NAVIDAD · NUESTRA RUTA',text:'Salzburg, St. Wolfgang, Hallstatt, Königssee, Berchtesgaden, Innsbruck y Zúrich, día a día.',image:'https://images.unsplash.com/photo-1504218727796-db522606b16f?auto=format&fit=crop&w=1000&q=88',available:true,href:'../../itinerarios/navidad-austria-alemania-suiza/'}],
 preparation:[{icon:'◷',title:'Navidad e invierno',text:'Nuestro viaje fue en Navidad, así que horarios de mercados, transporte y atracciones condicionaban mucho cada día.',image:'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=900&q=85',available:false},{icon:'✈',title:'Cómo llegamos',text:'Entramos por Múnich y continuamos en transporte público hasta Salzburg.',image:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=85',available:false},{icon:'🚆',title:'Moverse por Austria',text:'Nuestra ruta combinó tren, buses regionales y barco. La planificación de conexiones fue esencial.',image:'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=900&q=85',available:false},{icon:'⌖',title:'Nuestra ruta',text:'Salzburg fue la base para las excursiones antes de continuar hacia Innsbruck y después Zúrich.',image:'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=900&q=85',available:true,href:'../../itinerarios/navidad-austria-alemania-suiza/',ctaLabel:'VER ITINERARIO'},{icon:'⌂',title:'Alojamiento',text:'Dormimos en Salzburg y en Innsbruck, buscando ubicaciones prácticas para las conexiones.',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85',available:false},{icon:'€',title:'Presupuesto',text:'El presupuesto completo está todavía por cerrar y no publicaremos una cifra hasta tenerlo revisado.',image:'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&w=900&q=85',available:false}],
 faq:[{question:'¿Cuántos días estuvimos en Austria?',answer:'Nuestra ruta dedicó cuatro días a Austria antes de continuar hacia Zúrich.'},{question:'¿Dónde hicimos base?',answer:'Salzburg fue nuestra base para visitar la ciudad y hacer las excursiones a St. Wolfgang, Hallstatt, Königssee y Berchtesgaden.'},{question:'¿Cómo nos movimos?',answer:'Combinamos trenes, buses regionales y barco según cada etapa.'},{question:'¿Qué cambia al viajar en Navidad?',answer:'Los horarios de mercados, atracciones y transporte pueden variar, por lo que los revisamos para cada día.'},{question:'¿Hallstatt fue una noche aparte?',answer:'No. Lo visitamos como excursión y regresamos a Salzburg.'},{question:'¿St. Wolfgang y Hallstatt se pueden combinar?',answer:'Así lo organizamos nosotros: St. Wolfgang por la mañana y Hallstatt después.'}]
};
window.SWEDEN_CONTENT=window.COUNTRY_CONFIG;