(function(){
  function init(){
    const header=document.querySelector('.shared-header, .page-header'),nav=document.querySelector('.country-nav'),links=[...document.querySelectorAll('.country-nav a')],sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);
    let navTrigger=0;
    const spacer=document.createElement('div');spacer.className='country-nav-spacer';if(nav&&nav.parentNode)nav.parentNode.insertBefore(spacer,nav);
    const syncFixed=()=>{if(!nav)return;const hh=header?Math.round(header.getBoundingClientRect().height):0,nh=Math.round(nav.getBoundingClientRect().height),shouldFix=window.scrollY>=navTrigger;if(shouldFix){nav.classList.add('is-fixed');nav.style.position='fixed';nav.style.left='0';nav.style.right='0';nav.style.width='100%';nav.style.top=hh+'px';nav.style.zIndex='50';spacer.style.height=nh+'px'}else{nav.classList.remove('is-fixed');nav.style.position='relative';nav.style.left='';nav.style.right='';nav.style.width='';nav.style.top='';nav.style.zIndex='';spacer.style.height='0px'}};
    const syncSticky=()=>{const hh=header?Math.round(header.getBoundingClientRect().height):0,nh=nav?Math.round(nav.getBoundingClientRect().height):0;document.documentElement.style.setProperty('--vcc-header-h',hh+'px');document.documentElement.style.setProperty('--vcc-country-nav-h',nh+'px');if(nav&&!nav.classList.contains('is-fixed'))navTrigger=nav.getBoundingClientRect().top+window.scrollY-hh;syncFixed()};
    syncSticky();window.addEventListener('load',syncSticky);window.addEventListener('resize',syncSticky);window.addEventListener('scroll',syncFixed,{passive:true});
    links.forEach(a=>a.addEventListener('click',()=>{links.forEach(x=>x.classList.remove('active'));a.classList.add('active')}));if(links[0])links[0].classList.add('active');
    const setActive=()=>{if(!sections.length)return;const y=(header?header.getBoundingClientRect().height:0)+(nav?nav.getBoundingClientRect().height:0)+24;let current=sections[0];sections.forEach(s=>{if(s.getBoundingClientRect().top<=y)current=s});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current.id))};window.addEventListener('scroll',setActive,{passive:true});window.addEventListener('resize',setActive);setActive();
    const wireCarousel=(r,prev,next)=>{if(!r||!prev||!next)return;const update=()=>{prev.disabled=r.scrollLeft<4;next.disabled=r.scrollLeft+r.clientWidth>=r.scrollWidth-4};const step=()=>Math.max(r.clientWidth*.72,280);prev.onclick=()=>r.scrollBy({left:-step(),behavior:'smooth'});next.onclick=()=>r.scrollBy({left:step(),behavior:'smooth'});
      let active=false,axis='',sx=0,sy=0,startLeft=0,pid=null;
      r.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;active=true;axis='';sx=e.clientX;sy=e.clientY;startLeft=r.scrollLeft;pid=e.pointerId;r.classList.add('is-drag-ready')});
      r.addEventListener('pointermove',e=>{if(!active||e.pointerId!==pid)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(!axis&&Math.max(Math.abs(dx),Math.abs(dy))>6)axis=Math.abs(dx)>Math.abs(dy)*1.15?'x':'y';if(axis==='x'){e.preventDefault();if(!r.hasPointerCapture(pid))r.setPointerCapture(pid);r.classList.add('is-dragging');r.scrollLeft=startLeft-dx}});
      const end=()=>{if(!active)return;if(pid!==null&&r.hasPointerCapture(pid))r.releasePointerCapture(pid);active=false;axis='';pid=null;r.classList.remove('is-drag-ready','is-dragging');update()};
      r.addEventListener('pointerup',end);r.addEventListener('pointercancel',end);r.addEventListener('lostpointercapture',()=>{active=false;axis='';pid=null;r.classList.remove('is-drag-ready','is-dragging')});r.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update()};
    document.querySelectorAll('.country-carousel-wrap, .sweden-carousel-wrap').forEach(w=>wireCarousel(w.querySelector('.country-carousel, .sweden-carousel'),w.querySelector('[data-carousel-prev]'),w.querySelector('[data-carousel-next]')));
    const info=document.querySelector('[data-rating-info]'),note=document.querySelector('[data-rating-note]');if(info&&note)info.onclick=()=>{note.hidden=!note.hidden;info.setAttribute('aria-expanded',String(!note.hidden));const icon=info.querySelector('span');if(icon)icon.textContent=note.hidden?'＋':'−'};
    const faqItems=[...document.querySelectorAll('.vcc-faq-item')];faqItems.forEach(item=>item.addEventListener('toggle',()=>{if(item.open)faqItems.forEach(other=>{if(other!==item&&other.open)other.open=false});const summary=item.querySelector('summary'),b=summary&&summary.querySelector('b');if(summary)summary.setAttribute('aria-expanded',item.open?'true':'false');if(b)b.textContent=item.open?'−':'+';}));
  }
  function start(){if(document.querySelector('.country-nav, .country-template-main'))init();else window.addEventListener('vcc:country-rendered',init,{once:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();