window.COUNTRY_CONFIG={
 slug:'italia',name:'Italia',continent:'Europa',tagline:'Historia, arte y dos viajes muy diferentes',description:'Hemos descubierto Italia en dos viajes: una escapada a Milán y una ruta de 3 días por Roma que también nos llevó a la Ciudad del Vaticano.',heroImage:'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1800&q=88',inspirationImage:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1800&q=88',paths:{home:'../../index.html',destinations:'../index.html'},
 sections:{guides:{kicker:'Nuestros viajes a Italia',title:'CIUDADES QUE HEMOS VISITADO',description:'Dos escapadas independientes: Milán por un lado y Roma con la Ciudad del Vaticano por otro.'},itineraries:{kicker:'Nuestra ruta real',title:'ITINERARIOS EN ITALIA',description:'El recorrido que hicimos, organizado día a día y por zonas.',minimumCards:2},preparation:{kicker:'Antes de viajar a Italia',title:'PLANIFICA TU VIAJE',description:'Información práctica para preparar una escapada urbana a Italia.'},inspiration:{line1:'Italia siempre deja',line2:'ganas de volver'},faq:{kicker:'Antes de viajar',title:'PREGUNTAS FRECUENTES',description:'Lo esencial para preparar Roma, Vaticano o Milán.',sideLine1:'Dos viajes',sideLine2:'dos ciudades',sideLine3:'mil recuerdos'}},
 facts:[['VIAJES','2 diferentes'],['CIUDADES','Roma · Milán'],['OTRO ESTADO','Ciudad del Vaticano'],['MONEDA','Euro · EUR']],
 guides:[
 {title:'Roma + Vaticano',tag:'VIAJE 1 · GUÍA COMPLETA',image:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1000&q=88',text:'Roma histórica, plazas, barrios y una jornada que incluye la Ciudad del Vaticano.',days:'3 días',scores:{experience:9.4,photogenic:9.7,things:10,food:9.3,transport:8.3,safety:8.8,value:8.5},available:true,href:'roma/'},
 {title:'Milán',tag:'VIAJE 2 · CIUDAD',image:'https://images.unsplash.com/photo-1520440229-6469a149ac59?auto=format&fit=crop&w=1000&q=88',text:'Duomo, arquitectura, diseño y el ambiente de una ciudad elegante y moderna.',days:'Escapada urbana',scores:{experience:8.4,photogenic:8.8,things:8.1,food:8.8,transport:9.1,safety:8.8,value:7.7},available:false}
 ],
 itineraries:[{title:'Roma en 3 días',tag:'3 DÍAS · ROMA + VATICANO',text:'Nuestra ruta real: Vaticano, Roma histórica y centro de Roma, organizada día a día.',image:'https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&w=1000&q=88',available:true,href:'roma/itinerario.html'}],
 preparation:[{icon:'◷',title:'Cuándo ir',text:'Primavera y otoño suelen ofrecer temperaturas más cómodas para caminar.',image:'https://images.unsplash.com/photo-1529154036614-a60975f5c760?auto=format&fit=crop&w=900&q=85',available:false},{icon:'✈',title:'Cómo llegar',text:'Comparamos aeropuertos y conexiones para Roma y Milán.',image:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=85',available:false},{icon:'🚇',title:'Cómo moverse',text:'Centros muy caminables combinados con metro, tranvía o autobús.',image:'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=900&q=85',available:false},{icon:'⌖',title:'Ruta de Roma',text:'Tres días agrupados por zonas para aprovechar el tiempo.',image:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=900&q=85',available:true,href:'roma/itinerario.html',ctaLabel:'VER ITINERARIO'},{icon:'⌂',title:'Dónde alojarse',text:'Zonas prácticas para moverse bien sin pagar solo por estar en el centro.',image:'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=900&q=85',available:false},{icon:'🍝',title:'Gastronomía',text:'Platos típicos y pistas para alejarse de los menús más turísticos.',image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85',available:false}],
 faq:[{category:'VIAJES',icon:'✈',question:'¿Roma y Milán fueron el mismo viaje?',answer:'No. Los visitamos en dos viajes diferentes.'},{category:'RUTA',icon:'▣',question:'¿Cuántos días dedicamos a Roma?',answer:'Nuestra ruta completa fue de 3 días e incluyó la Ciudad del Vaticano.'},{category:'VATICANO',icon:'⌖',question:'¿La Ciudad del Vaticano forma parte del itinerario?',answer:'Sí. La visitamos durante el primer día del viaje a Roma.'},{category:'CÓMO MOVERSE',icon:'♙',question:'¿Roma se puede recorrer a pie?',answer:'Buena parte del itinerario se hace caminando, aunque conviene combinarlo con transporte público según el alojamiento.'},{category:'ENTRADAS',icon:'▤',question:'¿Qué conviene reservar?',answer:'Las visitas más demandadas, como los Museos Vaticanos y el Coliseo, conviene reservarlas con antelación.'},{category:'MILÁN',icon:'◇',question:'¿La guía de Milán ya está disponible?',answer:'Todavía la estamos preparando. Aparecerá como disponible cuando esté terminada.'}]
};window.SWEDEN_CONTENT=window.COUNTRY_CONFIG;
