(function(){
function init(){
  const header=document.querySelector('.page-header'),nav=document.querySelector('.country-nav'),links=[...document.querySelectorAll('.country-nav a')],sections=['guias','itinerarios','faq','planifica','planificador'].map(id=>document.getElementById(id)).filter(Boolean);
  let navTrigger=0;
  const spacer=document.createElement('div');spacer.className='country-nav-spacer';if(nav&&nav.parentNode)nav.parentNode.insertBefore(spacer,nav);
  const syncSticky=()=>{const hh=header?Math.round(header.getBoundingClientRect().height):0,nh=nav?Math.round(nav.getBoundingClientRect().height):0;document.documentElement.style.setProperty('--vcc-header-h',hh+'px');document.documentElement.style.setProperty('--vcc-country-nav-h',nh+'px');if(nav&&!nav.classList.contains('is-fixed'))navTrigger=nav.getBoundingClientRect().top+window.scrollY-hh;spacer.style.height=nav&&nav.classList.contains('is-fixed')?nh+'px':'0px';syncFixed()};
  const syncFixed=()=>{if(!nav)return;const hh=header?Math.round(header.getBoundingClientRect().height):0,nh=Math.round(nav.getBoundingClientRect().height);const shouldFix=window.scrollY>=navTrigger;if(shouldFix!==nav.classList.contains('is-fixed')){nav.classList.toggle('is-fixed',shouldFix);spacer.style.height=shouldFix?nh+'px':'0px'}nav.style.top=shouldFix?hh+'px':''};
  syncSticky();window.addEventListener('load',syncSticky);window.addEventListener('resize',syncSticky);window.addEventListener('scroll',syncFixed,{passive:true});
  links.forEach(a=>a.addEventListener('click',()=>{links.forEach(x=>x.classList.remove('active'));a.classList.add('active')}));if(links[0])links[0].classList.add('active');
  const setActive=()=>{const y=(header?header.getBoundingClientRect().height:0)+(nav?nav.getBoundingClientRect().height:0)+24;let current=sections[0];sections.forEach(s=>{if(s.getBoundingClientRect().top<=y)current=s});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current.id))};window.addEventListener('scroll',setActive,{passive:true});window.addEventListener('resize',setActive);setActive();
  const wireCarousel=(r,prev,next)=>{if(!r||!prev||!next)return;const update=()=>{prev.disabled=r.scrollLeft<4;next.disabled=r.scrollLeft+r.clientWidth>=r.scrollWidth-4};const step=()=>Math.max(r.clientWidth*.72,280);prev.onclick=()=>r.scrollBy({left:-step(),behavior:'smooth'});next.onclick=()=>r.scrollBy({left:step(),behavior:'smooth'});r.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update()};
  document.querySelectorAll('.sweden-carousel-wrap').forEach(w=>wireCarousel(w.querySelector('.sweden-carousel'),w.querySelector('[data-carousel-prev]'),w.querySelector('[data-carousel-next]')));
  const faq=document.querySelector('[data-faq-carousel]');if(faq){const wrap=faq.closest('.faq-carousel-wrap');wireCarousel(faq,wrap.querySelector('[data-faq-prev]'),wrap.querySelector('[data-faq-next]'))}
  const info=document.querySelector('[data-rating-info]'),note=document.querySelector('[data-rating-note]');if(info&&note)info.onclick=()=>{note.hidden=!note.hidden;info.setAttribute('aria-expanded',String(!note.hidden));info.querySelector('span').textContent=note.hidden?'＋':'−'};
  const planner=document.querySelector('[data-sweden-planner]'),form=planner&&planner.querySelector('form');if(planner&&form)setupPlanner(planner,form);
}
function setupPlanner(box,form){const c=window.SWEDEN_CONTENT,out=box.querySelector('.planner-result');if(!c||!out)return;const pool=[...c.itineraries,...c.guides],seasonFit={'Estocolmo':{verano:4,primavera:3,otono:2,invierno:3},'Gotemburgo':{verano:4,primavera:3,otono:2,invierno:1},'Costa Oeste':{verano:6,primavera:2,otono:0,invierno:-9},'Dalarna':{verano:4,primavera:2,otono:3,invierno:2},'Zona de los Lagos':{verano:5,primavera:2,otono:2,invierno:-5},'Estocolmo en 3 días':{verano:4,primavera:3,otono:2,invierno:3},'Estocolmo + Dalarna en 7 días':{verano:6,primavera:2,otono:3,invierno:1},'Suecia en 14 días':{verano:7,primavera:1,otono:1,invierno:-10}};
  const action=x=>x.available&&x.href?`<a class="country-btn planner-main-btn" href="${x.href}">${x.tag&&x.tag.includes('DÍAS')?'VER ITINERARIO':'VER NUESTRA GUÍA'} →</a>`:`<a class="planner-fallback" href="#guias">VER GUÍAS DE SUECIA ↑</a>`;
  form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),days=+fd.get('days'),move=fd.get('transport'),season=fd.get('season'),likes=fd.getAll('interest');const ranked=pool.map(x=>{let s=days>=x.minDays&&days<=x.maxDays?8:Math.max(0,5-Math.abs(days-(x.minDays+x.maxDays)/2));if(move)s+=x.transports.includes(move)?4:-2;s+=likes.filter(v=>x.interests.includes(v)).length*4;if(season&&seasonFit[x.title])s+=seasonFit[x.title][season]||0;return{x,s}}).sort((a,b)=>b.s-a.s),top=ranked[0].x,alts=ranked.slice(1,3).map(r=>r.x);const selected=[...form.querySelectorAll('input:checked+span')].map(x=>x.textContent.trim()).filter(Boolean);out.innerHTML=`<div class="planner-result-primary"><span>TU RUTA VCC</span><h3>${top.title.toUpperCase()}</h3><p>${top.text}</p><div class="planner-match">${selected.slice(0,4).map(x=>`<i>${x}</i>`).join('')}</div><small>Es la opción que mejor encaja con las preferencias que has marcado.</small>${action(top)}</div>${alts.length?`<div class="planner-alternatives"><span>SI QUIERES COMPARAR</span>${alts.map(x=>`<a ${x.available&&x.href?`href="${x.href}"`:''} class="planner-alt ${x.available&&x.href?'is-link':''}">${x.title}</a>`).join('')}</div>`:''}`;out.hidden=false;out.scrollIntoView({behavior:'smooth',block:'nearest'})}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();