(function(){
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const W={experience:25,photogenic:20,things:15,food:10,transport:10,safety:10,value:10};
function rating(s){return Object.keys(W).reduce((n,k)=>n+(Number(s&&s[k])||0)*W[k]/100,0)}
function fmt(n){return n.toFixed(1).replace('.',',')}
function label(n){return n>=9.5?'Excepcional · Espectacular':n>=9?'Fantástico':n>=8.5?'Fabuloso':n>=8?'Muy bien':n>=7.5?'Bien':n>=7?'Agradable':'Mejorable'}
function guide(g){const r=rating(g.scores);return `<article class="country-guide-card"><div class="guide-image-wrap"><img src="${esc(g.image)}" alt="${esc(g.title)}" loading="lazy"><div class="guide-score"><strong>${fmt(r)}</strong><span>${label(r)}</span></div></div><div class="country-guide-copy"><span class="tag">${esc(g.tag)}</span><h3>${esc(g.title).toUpperCase()}</h3><p>${esc(g.text)}</p><div class="country-meta"><span>◷ ${esc(g.days)}</span></div><div class="vcc-card-action">${g.available&&g.href?`<a class="country-btn" href="${esc(g.href)}">VER GUÍA →</a>`:'<span class="country-soon">PRÓXIMAMENTE</span>'}</div></div></article>`}
function itinerary(i){return `<article class="country-itinerary"><img src="${esc(i.image)}" alt="${esc(i.title)}" loading="lazy"><div class="country-itinerary-copy"><span class="tag">${esc(i.tag)}</span><h3>${esc(i.title).toUpperCase()}</h3><p>${esc(i.text)}</p><div class="vcc-card-action">${i.available&&i.href?`<a class="country-btn" href="${esc(i.href)}">VER ITINERARIO →</a>`:'<span class="country-soon">PRÓXIMAMENTE</span>'}</div></div></article>`}
function itineraryPlaceholder(){return `<article class="country-itinerary vcc-placeholder"><div class="vcc-placeholder-image"><span>VCC</span></div><div class="country-itinerary-copy"><span class="tag">NUEVA RUTA</span><h3>PRÓXIMO ITINERARIO</h3><p>Estamos preparando una nueva ruta por Suecia para ampliar las opciones de viaje.</p><div class="vcc-card-action"><span class="country-soon">PRÓXIMAMENTE</span></div></div></article>`}
function carousel(items,type){return `<div class="sweden-carousel-wrap vcc-four-carousel"><button class="carousel-arrow prev" data-carousel-prev aria-label="Anterior">←</button><div class="sweden-carousel" data-carousel="${type}">${items}</div><button class="carousel-arrow next" data-carousel-next aria-label="Siguiente">→</button></div>`}
function prepCard(x){return `<article class="vcc-prep-card"><div class="vcc-prep-image"><img src="${esc(x.image)}" alt="${esc(x.title)}" loading="lazy"><span>${esc(x.icon)}</span></div><div class="vcc-prep-copy"><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p><div class="vcc-card-action">${x.available&&x.href?`<a class="vcc-prep-action" href="${esc(x.href)}">${esc(x.ctaLabel||'VER MÁS')} →</a>`:'<span class="vcc-soon">PRÓXIMAMENTE</span>'}</div></div></article>`}
function faq(x,n){return `<details class="vcc-faq-item"><summary><span class="vcc-faq-number">${String(n+1).padStart(2,'0')}</span><span class="vcc-faq-question">${esc(x.question)}</span><b aria-hidden="true">+</b></summary><div class="vcc-faq-answer"><p>${esc(x.answer)}</p></div></details>`}
function render(){const c=window.SWEDEN_CONTENT,root=document.getElementById('country-content');if(!c||!root)return;const facts=c.facts.map(x=>`<div class="country-fact"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join('');const itin=[...c.itineraries];while(itin.length<4)itin.push(null);root.innerHTML=`
<section class="country-hero" style="background-image:url('${esc(c.heroImage)}')"><div class="country-hero-inner"><div class="country-breadcrumb"><a href="../../index.html">Inicio</a><span>›</span><a href="../index.html">Destinos</a><span>›</span><strong>Suecia</strong></div><div class="country-hero-card"><div class="country-eyebrow">📍 EUROPA</div><h1>SUECIA</h1><p class="country-script">${esc(c.tagline)}</p><p class="country-desc">${esc(c.description)}</p><div class="country-facts">${facts}</div><a class="hero-start" href="#guias">EMPIEZA A EXPLORAR ↓</a></div></div></section>
<nav class="country-nav"><div class="country-nav-inner"><a href="#guias">GUÍAS</a><a href="#itinerarios">ITINERARIOS</a><a href="#planifica">PLANIFICA TU VIAJE</a><a href="#faq">PREGUNTAS FRECUENTES</a></div></nav>
<main class="country-main sweden-main vcc-sweden-page">
<section id="guias"><div class="country-heading"><div><p>Descubre Suecia</p><h2>GUÍAS DE VIAJE</h2></div><span>Ciudades, regiones y rincones para encontrar la Suecia que mejor encaja contigo.</span></div>${carousel(c.guides.map(guide).join(''),'guides')}<button class="vcc-rating-info" type="button" data-rating-info aria-expanded="false">¿Cómo calculamos la Nota VCC? <span>＋</span></button><div class="vcc-rating-note" data-rating-note hidden><strong>Una nota editorial VCC.</strong> Valoramos qué ver y hacer, gastronomía, transporte, seguridad, calidad-precio, fotogenia y experiencia global.</div></section>
<section id="itinerarios" class="sweden-itineraries-section"><div class="country-heading"><div><p>Combina las piezas</p><h2>ITINERARIOS EN SUECIA</h2></div><span>Rutas listas para organizar el viaje según los días que tengas.</span></div>${carousel(itin.map(x=>x?itinerary(x):itineraryPlaceholder()).join(''),'itineraries')}</section>
<section id="planifica" class="vcc-plan-section"><div class="country-heading"><div><p>ANTES DE VIAJAR A SUECIA</p><h2>PLANIFICA TU VIAJE</h2></div><span>Información práctica y nuestra opinión para preparar Suecia sin perder tiempo en lo que realmente importa.</span></div><div class="vcc-prep-grid">${c.preparation.map(prepCard).join('')}</div></section>
<section class="vcc-inspiration" style="background-image:url('${esc(c.inspirationImage)}')"><div><p>Viaja mejor,</p><strong>viaja con cabeza</strong></div></section>
<section id="faq" class="vcc-faq-section"><div class="vcc-faq-top"><div class="vcc-faq-title"><p class="vcc-faq-kicker">ANTES DE HACER LA MALETA</p><h2>LO QUE SIEMPRE<br>TE PREGUNTAS</h2></div><div class="vcc-faq-side"><div class="vcc-faq-brandmark" aria-hidden="true"></div><p>Diez respuestas directas para preparar Suecia con las ideas claras y sin perder tiempo buscando lo esencial.</p></div></div><div class="vcc-faq-grid">${c.faq.map(faq).join('')}</div></section>
</main>`;
root.querySelectorAll('.vcc-faq-item').forEach(item=>item.addEventListener('toggle',()=>{const b=item.querySelector('summary b');if(b)b.textContent=item.open?'−':'+'}));
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();