(function(){
function init(){
  const nav=document.querySelector('.country-nav'),links=[...document.querySelectorAll('.country-nav a')],sections=['guias','itinerarios','faq','planifica'].map(id=>document.getElementById(id)).filter(Boolean);
  links.forEach(a=>a.addEventListener('click',()=>{links.forEach(x=>x.classList.remove('active'));a.classList.add('active')}));if(links[0])links[0].classList.add('active');
  const setActive=()=>{const y=(nav?nav.getBoundingClientRect().height:0)+120;let current=sections[0];sections.forEach(s=>{if(s.getBoundingClientRect().top<=y)current=s});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current.id))};window.addEventListener('scroll',setActive,{passive:true});window.addEventListener('resize',setActive);setActive();
  document.querySelectorAll('.sweden-carousel-wrap').forEach(w=>{const r=w.querySelector('.sweden-carousel'),step=()=>Math.max(r.clientWidth*.72,280);w.querySelector('[data-carousel-prev]').onclick=()=>r.scrollBy({left:-step(),behavior:'smooth'});w.querySelector('[data-carousel-next]').onclick=()=>r.scrollBy({left:step(),behavior:'smooth'})});
  const faq=document.querySelector('[data-faq-carousel]');if(faq){const wrap=faq.closest('.faq-carousel-wrap'),step=()=>Math.max(faq.clientWidth*.72,280);wrap.querySelector('[data-faq-prev]').onclick=()=>faq.scrollBy({left:-step(),behavior:'smooth'});wrap.querySelector('[data-faq-next]').onclick=()=>faq.scrollBy({left:step(),behavior:'smooth'})}
  const info=document.querySelector('[data-rating-info]'),note=document.querySelector('[data-rating-note]');if(info&&note)info.onclick=()=>{note.hidden=!note.hidden;info.textContent=note.hidden?'¿Cómo calculamos la Nota VCC?':'Ocultar cómo calculamos la Nota VCC'};
  const planner=document.querySelector('[data-sweden-planner]'),form=planner&&planner.querySelector('form');if(planner&&form)setupPlanner(planner,form);
}
function setupPlanner(box,form){const c=window.SWEDEN_CONTENT,out=box.querySelector('.planner-result');if(!c||!out)return;const pool=[...c.itineraries,...c.guides],seasonFit={'Estocolmo':{verano:4,primavera:3,otono:2,invierno:3},'Gotemburgo':{verano:4,primavera:3,otono:2,invierno:1},'Costa Oeste':{verano:6,primavera:2,otono:0,invierno:-9},'Dalarna':{verano:4,primavera:2,otono:3,invierno:2},'Zona de los Lagos':{verano:5,primavera:2,otono:2,invierno:-5},'Estocolmo en 3 días':{verano:4,primavera:3,otono:2,invierno:3},'Estocolmo + Dalarna en 7 días':{verano:6,primavera:2,otono:3,invierno:1},'Suecia en 14 días':{verano:7,primavera:1,otono:1,invierno:-10}};
  const action=x=>x.available&&x.href?`<a class="country-btn planner-main-btn" href="${x.href}">${x.tag&&x.tag.includes('DÍAS')?'VER ITINERARIO':'VER NUESTRA GUÍA'} →</a>`:`<span class="country-soon">CONTENIDO · PRÓXIMAMENTE</span>`;
  form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),days=+fd.get('days'),move=fd.get('transport'),season=fd.get('season'),likes=fd.getAll('interest');const ranked=pool.map(x=>{let s=days>=x.minDays&&days<=x.maxDays?8:Math.max(0,5-Math.abs(days-(x.minDays+x.maxDays)/2));if(move)s+=x.transports.includes(move)?4:-2;s+=likes.filter(v=>x.interests.includes(v)).length*4;if(season&&seasonFit[x.title])s+=seasonFit[x.title][season]||0;return{x,s}}).sort((a,b)=>b.s-a.s),top=ranked[0].x,alts=ranked.slice(1,3).map(r=>r.x);out.innerHTML=`<div class="planner-result-primary"><span>TU RUTA VCC</span><h3>${top.title.toUpperCase()}</h3><p>${top.text}</p><small>La hemos priorizado según tus días, intereses, transporte y época del año.</small>${action(top)}</div>${alts.length?`<div class="planner-alternatives"><span>TAMBIÉN PODRÍAN ENCAJARTE</span>${alts.map(x=>`<a ${x.available&&x.href?`href="${x.href}"`:''} class="planner-alt ${x.available&&x.href?'is-link':''}">${x.title}</a>`).join('')}</div>`:''}`;out.hidden=false;out.scrollIntoView({behavior:'smooth',block:'nearest'})}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();